// ──────────────────────────────────────────────────────────────────────────
// anchormovies HLS gate — Cloudflare Worker
// Serves the private R2 bucket ONLY with a valid, unexpired signed token, and
// only to your own player (Referer/Origin gate). Netmirror-style.
//
// Playback URL your site hands out (generated by the signer, 24h life):
//   https://<worker>/movies/<slug>/master.m3u8?t=<exp>.<hmac>
// The Worker validates the token, rewrites the .m3u8 so every child playlist &
// segment carries the same token, adds CORS, and streams bytes from R2.
//
// DOWNLOADS — https://<worker>/downloads/<slug>/<file>?t=<exp>.<hmac>
// Same token, same 24h life, but NO origin gate. A download has to work from a
// download manager, a pasted link, or a browser sending no referrer, and the
// signature is already the authorization. Streaming keeps the gate, because
// there the point is stopping another site embedding our player.
//
// Bindings/vars to set on the Worker (dashboard → Settings):
//   • R2 bucket binding:  BUCKET  → anchormovies
//   • For B2 (only if you store there): B2_KEY_ID, B2_APP_KEY (secrets),
//     B2_BUCKET (e.g. anchormov), B2_ENDPOINT (e.g. s3.us-east-005.backblazeb2.com)
//   • Secret:  SIGNING_SECRET  → (the hex secret from ~/.r2/credentials.env)
// Two storage backends live behind this one gate:
//   movies/<slug>/...      → Cloudflare R2   (the BUCKET binding)
//   b2/movies/<slug>/...   → Backblaze B2    (S3 API, signed per request)
// The token is scoped to movies/<slug> either way, so links and the 24h signer
// are identical for both.
//
//   • Variable: ALLOWED_HOSTS  → every site that plays our streams, comma list
//        e.g. 1anchormovies.live,1anchormovies.buzz,localhost   (blank = allow any)
//        NOTE: a site missing from this list gets 403 on every segment.
//   • Variable: DOWNLOAD_PREFIX → path prefix exempt from the origin gate
//        (default "downloads/")
//
// Segments are immutable, so they're cached at the Cloudflare edge AFTER the
// origin+token gate — the second viewer in a city reads from that city instead
// of from R2. Playlists stay no-store (they're rewritten per token).
// ──────────────────────────────────────────────────────────────────────────

const te = new TextEncoder();

async function hmacHex(secret, msg) {
  const key = await crypto.subtle.importKey("raw", te.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("HMAC", key, te.encode(msg));
  return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
function timingEq(a, b) {
  if (a.length !== b.length) return false;
  let r = 0;
  for (let i = 0; i < a.length; i++) r |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return r === 0;
}

// token = "<exp>.<hmac>"  where hmac = HMAC(secret, "<prefix>:<exp>")
// prefix = "movies/<slug>" — so one token unlocks that movie's whole folder for 24h.
async function verifyToken(secret, prefix, token) {
  if (!token || !token.includes(".")) return false;
  const [exp, sig] = token.split(".");
  if (!/^\d+$/.test(exp)) return false;
  if (Number(exp) * 1000 < Date.now()) return false; // expired
  const expect = await hmacHex(secret, `${prefix}:${exp}`);
  return timingEq(sig, expect);
}

/* ── Backblaze B2 (S3 API) ────────────────────────────────────────────────
   Workers have no B2 binding, so GETs are signed with AWS SigV4 by hand.
   Only host/x-amz-date/x-amz-content-sha256 are signed — Range is deliberately
   left unsigned so byte-range requests pass straight through. */
async function hmac(key, msg) {
  const k = await crypto.subtle.importKey("raw", key, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return new Uint8Array(await crypto.subtle.sign("HMAC", k, te.encode(msg)));
}
const hex = (buf) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
async function sha256Hex(msg) {
  return hex(await crypto.subtle.digest("SHA-256", te.encode(msg)));
}

// Returns the names of any B2 settings that are missing, so a misconfigured
// Worker says WHICH one rather than a blank "not configured".
function b2Missing(env) {
  return ["B2_KEY_ID", "B2_APP_KEY", "B2_BUCKET", "B2_ENDPOINT"].filter((k) => !env[k]);
}

async function b2Fetch(env, objKey, req) {
  const host = (env.B2_ENDPOINT || "").replace(/^https?:\/\//, "").replace(/\/$/, "");
  const bucket = env.B2_BUCKET || "";
  if (!host || !bucket || !env.B2_KEY_ID || !env.B2_APP_KEY) return null;

  // region is embedded in the endpoint: s3.us-east-005.backblazeb2.com → us-east-005
  const region = (host.match(/^s3\.([^.]+)\./) || [])[1] || "us-east-005";
  const canonicalUri = "/" + [bucket, ...objKey.split("/")].map(encodeURIComponent).join("/");
  const now = new Date().toISOString().replace(/[:-]|\.\d{3}/g, "");   // 20260806T101500Z
  const date = now.slice(0, 8);
  const payloadHash = "UNSIGNED-PAYLOAD";

  const canonicalHeaders = `host:${host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${now}\n`;
  const signedHeaders = "host;x-amz-content-sha256;x-amz-date";
  const canonicalRequest = ["GET", canonicalUri, "", canonicalHeaders, signedHeaders, payloadHash].join("\n");

  const scope = `${date}/${region}/s3/aws4_request`;
  const stringToSign = ["AWS4-HMAC-SHA256", now, scope, await sha256Hex(canonicalRequest)].join("\n");

  let k = await hmac(te.encode("AWS4" + env.B2_APP_KEY), date);
  k = await hmac(k, region);
  k = await hmac(k, "s3");
  k = await hmac(k, "aws4_request");
  const signature = hex(await hmac(k, stringToSign));

  const headers = new Headers({
    "x-amz-content-sha256": payloadHash,
    "x-amz-date": now,
    authorization: `AWS4-HMAC-SHA256 Credential=${env.B2_KEY_ID}/${scope}, `
      + `SignedHeaders=${signedHeaders}, Signature=${signature}`,
  });
  const range = req.headers.get("Range");
  if (range) headers.set("Range", range);          // unsigned, passed through

  return fetch(`https://${host}${canonicalUri}`, { method: "GET", headers });
}

/* ── Google Drive delivery ────────────────────────────────────────────────
   Files live on Drive (5TB already paid for) and Cloudflare serves them, so
   nothing is stored twice and no bandwidth comes off our own box. The Drive web
   endpoint interrupts anything over ~100MB with a virus-scan page; the API does
   not, which is why this goes through the API with a Bearer token.

   Secrets: GDRIVE_CLIENT_ID, GDRIVE_CLIENT_SECRET, GDRIVE_REFRESH_TOKEN. */
let driveToken = { value: null, expires: 0 };

async function driveAccessToken(env) {
  if (driveToken.value && Date.now() < driveToken.expires - 60_000) return driveToken.value;
  const body = new URLSearchParams({
    client_id: env.GDRIVE_CLIENT_ID,
    client_secret: env.GDRIVE_CLIENT_SECRET,
    refresh_token: env.GDRIVE_REFRESH_TOKEN,
    grant_type: "refresh_token",
  });
  const r = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body,
  });
  if (!r.ok) throw new Error(`drive token ${r.status}`);
  const j = await r.json();
  // Cached on the isolate: a cold one spends a single extra round trip.
  driveToken = { value: j.access_token, expires: Date.now() + (j.expires_in || 3600) * 1000 };
  return driveToken.value;
}

async function driveFetch(env, fileId, req) {
  const token = await driveAccessToken(env);
  const headers = { Authorization: `Bearer ${token}` };
  const range = req.headers.get("Range");
  if (range) headers.Range = range;              // resume passes straight through
  return fetch(
    `https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?alt=media&supportsAllDrives=true`,
    { headers }
  );
}

function cors(resp, origin) {
  const h = new Headers(resp.headers);
  h.set("Access-Control-Allow-Origin", origin || "*");
  h.set("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS");
  h.set("Access-Control-Allow-Headers", "Range,Content-Type");
  h.set("Access-Control-Expose-Headers", "Content-Length,Content-Range,ETag");
  h.set("Vary", "Origin");
  return new Response(resp.body, { status: resp.status, headers: h });
}

export default {
  async fetch(req, env, ctx) {
    const url = new URL(req.url);
    const origin = req.headers.get("Origin") || "*";
    if (req.method === "OPTIONS") return cors(new Response(null, { status: 204 }), origin);

    const key = decodeURIComponent(url.pathname.replace(/^\/+/, "")); // movies/slug/master.m3u8
    if (!key) return new Response("anchormovies gate", { status: 200 });

    /* A download is a different contract from playback. The origin gate exists
       to stop another site embedding our player; a download link has no player
       to embed, and it must survive being pasted into a new tab, handed to a
       download manager, or opened by a browser that sends no referrer. The
       signature is the authorization there, and it still expires in 24h. */
    const dlPrefix = (env.DOWNLOAD_PREFIX || "downloads/").replace(/^\/+/, "");
    const isDownload = key.startsWith(dlPrefix) || key.startsWith(`b2/${dlPrefix}`)
      || key.startsWith("drive/");

    // 1) only your player(s) — Referer/Origin gate (playback only)
    const allow = (env.ALLOWED_HOSTS || "").split(",").map((s) => s.trim()).filter(Boolean);
    const ref = req.headers.get("Referer") || req.headers.get("Origin") || "";
    if (!isDownload && allow.length && !allow.some((h) => ref.includes(h))) {
      return cors(new Response("Forbidden origin", { status: 403 }), origin);
    }

    // 1b) which backend? "b2/movies/<slug>/..." goes to Backblaze, everything
    //     else stays on R2 — so every link minted before B2 existed still works.
    const onB2 = key.startsWith("b2/");
    const objKey = onB2 ? key.slice(3) : key;          // movies/<slug>/file

    // 2) token valid + not expired, scoped to this movie folder. The scope is
    //    movies/<slug> on BOTH backends, so the signer needs no special case.
    //    Downloads are scoped the same way: downloads/<slug>.
    const token = url.searchParams.get("t") || "";
    const prefix = objKey.split("/").slice(0, 2).join("/"); // movies/<slug>
    if (!(await verifyToken(env.SIGNING_SECRET, prefix, token))) {
      return cors(new Response("Link expired or invalid", { status: 403 }), origin);
    }

    /* 2b) drive/<fileId>/<filename> — served from Drive, not from a bucket.
           The token is scoped to drive/<fileId> by the same rule as everything
           else, so the signer needs no special case. */
    if (objKey.startsWith("drive/")) {
      if (!env.GDRIVE_REFRESH_TOKEN) {
        return cors(new Response("Drive delivery is not configured", { status: 500 }), origin);
      }
      const [, fileId, ...rest] = objKey.split("/");
      if (!fileId) return cors(new Response("Not found", { status: 404 }), origin);
      let up;
      try {
        up = await driveFetch(env, fileId, req);
      } catch (e) {
        return cors(new Response(`Drive: ${e.message}`, { status: 502 }), origin);
      }
      if (up.status === 404) return cors(new Response("Not found", { status: 404 }), origin);
      if (!up.ok && up.status !== 206) {
        return cors(new Response(`Upstream ${up.status}`, { status: 502 }), origin);
      }
      const h = new Headers();
      for (const k of ["content-type", "content-length", "content-range", "etag", "last-modified"]) {
        const v = up.headers.get(k);
        if (v) h.set(k, v);
      }
      h.set("accept-ranges", "bytes");
      const filename = decodeURIComponent(rest.join("/") || fileId).replace(/["\\]/g, "");
      /* A Drive file is now BOTH the download and what the player streams, so
         the disposition cannot be fixed at "attachment": that tells the browser
         to save rather than render, which is why opening one in a tab produced
         a download instead of a video. Download buttons ask for it explicitly
         with ?dl=1; everything else is served inline, still with the right
         filename should the viewer save it. */
      const wantsDownload = url.searchParams.get("dl") === "1";
      h.set("content-disposition",
        `${wantsDownload ? "attachment" : "inline"}; filename="${filename}"`);

      /* A video is fetched as dozens of separate range requests, and the browser
         will only stitch those into one media stream if it can prove they came
         from the same object AND it is allowed to hold them. Drive sends no
         ETag of its own, and no-store forbids the media cache outright, so
         playback sat at readyState 0 with no progress event ever firing — the
         bytes arrived, nothing consumed them. A stable validator derived from
         the file id and its length gives the browser both. Access is still
         governed entirely by the signed token; "private" keeps this out of any
         shared cache. */
      if (!h.get("etag")) h.set("etag", `"drive-${fileId}-${up.headers.get("content-range")?.split("/")[1] || up.headers.get("content-length") || "0"}"`);
      h.set("cache-control", wantsDownload ? "no-store" : "private, max-age=3600");
      h.set("x-source", "drive");
      return cors(new Response(up.body, { status: up.status, headers: h }), origin);
    }

    // 3) edge cache — segments only, and only for whole-object GETs.
    //    The cache key deliberately DROPS the ?t= token: every session gets a
    //    fresh token, so keying on the full URL would never hit. The gate above
    //    has already run, so nothing unauthorised can reach this.
    const range = req.headers.get("Range");
    const isPlaylist = objKey.endsWith(".m3u8");
    // GET only — a HEAD must not be answered with a cached body.
    const cacheable = !isPlaylist && !range && req.method === "GET";
    const cache = caches.default;
    const cacheKey = new Request(new URL(url.pathname, url.origin).toString(), { method: "GET" });

    if (cacheable) {
      const hit = await cache.match(cacheKey);
      if (hit) {
        const h = new Response(hit.body, { status: hit.status, headers: new Headers(hit.headers) });
        h.headers.set("x-cache", "HIT");
        return cors(h, origin);
      }
    }

    // 4) fetch the object from whichever backend holds it
    let body, headers = new Headers(), size = 0, objRange = null, upstreamStatus = 200;

    if (onB2) {
      const r = await b2Fetch(env, objKey, req);
      if (!r) return cors(new Response(`B2 not configured — missing: ${b2Missing(env).join(", ") || "none (check values)"}`, { status: 500 }), origin);
      if (r.status === 404) return cors(new Response("Not found", { status: 404 }), origin);
      if (!r.ok && r.status !== 206) {
        return cors(new Response(`Upstream ${r.status}`, { status: 502 }), origin);
      }
      body = r.body;
      upstreamStatus = r.status;
      for (const h of ["content-type", "content-length", "etag", "content-range", "last-modified"]) {
        const v = r.headers.get(h);
        if (v) headers.set(h, v);
      }
      size = Number(r.headers.get("content-length")) || 0;
    } else {
      const obj = await env.BUCKET.get(objKey, range ? { range: req.headers } : undefined);
      if (!obj) return cors(new Response("Not found", { status: 404 }), origin);
      body = obj.body;
      obj.writeHttpMetadata(headers);
      headers.set("etag", obj.httpEtag);
      size = obj.size;
      objRange = obj.range;
    }
    headers.set("accept-ranges", "bytes");
    // R2 sets obj.range even on a full read, so the 206/200 decision must come
    // from what the CLIENT asked for. Answering 206 to a plain GET is malformed
    // (no Content-Range) and, worse, the Cache API refuses to store a 206 — that
    // alone was silently disabling this whole cache.
    // B2 answers 206 + Content-Range itself; for R2 we decide, because R2 reports
    // obj.range even on a full read (a 206 there would be malformed AND uncacheable).
    const status = onB2 ? upstreamStatus : (range && objRange ? 206 : 200);
    if (!onB2 && status === 206) {
      const start = objRange.offset || 0;
      const len   = objRange.length ?? (size - start);
      headers.set("content-range", `bytes ${start}-${start + len - 1}/${size}`);
    }
    // Segments come out of storage with whatever type was guessed at upload
    // (often text/vnd.trolltech.linguist) — name them properly.
    if (objKey.endsWith(".ts")) headers.set("content-type", "video/mp2t");

    /* Downloads save rather than play: name the file and force the dialogue,
       or an .mp4 opens in the tab and lands in the cache with the wrong name. */
    if (isDownload) {
      const filename = objKey.split("/").pop().replace(/["\\]/g, "");
      headers.set("content-disposition", `attachment; filename="${filename}"`);
    }

    // Playlists carry per-session tokens → never store them. Segment bytes never
    // change for a given path, so they're safe to keep for a year.
    headers.set("cache-control", cacheable ? "public, max-age=31536000, immutable" : "no-store");

    // 5) rewrite playlists so children inherit the token. Children are relative
    //    names, so the b2/ prefix carries over from the parent URL automatically.
    if (isPlaylist) {
      let text = await new Response(body).text();
      const t = encodeURIComponent(token);
      // Match every child a playlist can reference: nested playlists (m3u8),
      // media segments (ts / fMP4 m4s/mp4/aac/m4a) AND subtitle segments (vtt).
      // vtt was missing before, so subtitle segments loaded without a token → 403.
      const EXT = "m3u8|ts|vtt|m4s|mp4|aac|m4a";
      text = text
        // URI="child.ext"  (audio/subtitle renditions in #EXT-X-MEDIA, incl. subtitle .vtt/.m3u8)
        .replace(new RegExp(`URI="([^"]+\\.(${EXT}))"`, "g"), (_m, p) => `URI="${p}?t=${t}"`)
        // bare lines: variant playlists + video/audio/subtitle segments
        .replace(new RegExp(`^([^#\\r\\n][^\\r\\n]*\\.(${EXT}))\\s*$`, "gm"), (_m, p) => `${p}?t=${t}`);
      headers.set("content-type", "application/vnd.apple.mpegurl");
      headers.delete("content-length");     // body length changed after rewriting
      return cors(new Response(text, { status: 200, headers }), origin);
    }

    headers.set("x-cache", cacheable ? "MISS" : "BYPASS");
    const resp = new Response(body, { status, headers });
    /* Store the pre-CORS copy: Access-Control-Allow-Origin varies per caller and
       is added on the way out (including on cache hits). Films are skipped —
       the Cache API tops out around 512MB, so a feature-length download would
       fail the put on every single request for no benefit. */
    const CACHE_MAX = 500 * 1024 * 1024;
    if (cacheable && status === 200 && size > 0 && size <= CACHE_MAX) {
      ctx.waitUntil(cache.put(cacheKey, resp.clone()));
    }
    return cors(resp, origin);
  },
};
